# Generated by Django 4.2.5 on 2023-09-24 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('price', models.IntegerField()),
                ('publisher', models.CharField(max_length=50)),
                ('page_numbers', models.CharField(max_length=5)),
                ('available_quantity', models.BooleanField()),
                ('publication_date', models.DateField()),
                ('edition', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='templates/images')),
                ('summery', models.TextField(default='this is summery of book', null=True)),
                ('translator', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PublisherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.book')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
